# Generated by Django 3.0.4 on 2021-07-30 02:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memo', to='make_trip.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_money', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, '0以上で入力してください')])),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='make_trip.Trip')),
            ],
        ),
    ]
